# Generated by Django 4.2.4 on 2024-06-15 02:22

from django.db import migrations, models
import django.contrib.gis.db.models.fields

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='KiharuBnd',
            fields=[
                ('fid', models.BigIntegerField(blank=True, null=True)),
                ('id_0', models.BigIntegerField(blank=True, null=True)),
                ('iso', models.CharField(max_length=3, blank=True, null=True)),
                ('name_0', models.CharField(max_length=75, blank=True, null=True)),
                ('id_1', models.BigIntegerField(blank=True, null=True)),
                ('name_1', models.CharField(max_length=75, blank=True, null=True)),
                ('id_2', models.BigIntegerField(blank=True, null=True)),
                ('name_2', models.CharField(max_length=75, blank=True, null=True)),
                ('hasc_2', models.CharField(max_length=15, blank=True, null=True)),
                ('ccn_2', models.BigIntegerField(blank=True, null=True)),
                ('cca_2', models.CharField(max_length=254, blank=True, null=True)),
                ('type_2', models.CharField(max_length=50, blank=True, null=True)),
                ('engtype_2', models.CharField(max_length=50, blank=True, null=True)),
                ('nl_name_2', models.CharField(max_length=75, blank=True, null=True)),
                ('varname_2', models.CharField(max_length=150, blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, blank=True, null=True)),
            ],
            options={
                'db_table': 'kiharu_bnd',
                'managed': False,
                'verbose_name_plural': 'Kiharu Bnd',
            },
        ),
        migrations.CreateModel(
            name='KiharuHealthFacilitiesCleaned',
            fields=[
                ('no', models.IntegerField(blank=True, null=True)),
                ('county', models.CharField(max_length=255, blank=True, null=True)),
                ('sub_county', models.CharField(db_column='sub county', max_length=255, blank=True, null=True)),
                ('name_of_health_facility', models.CharField(db_column='name of health facility', max_length=255, blank=True, null=True)),
                ('mfl_number', models.IntegerField(db_column='mfl number', blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('contact', models.CharField(max_length=255, blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, blank=True, null=True)),
                ('picture1', models.ImageField(upload_to='pictures/%Y/%m/%d/', blank=True, null=True)),
                ('picture2', models.ImageField(upload_to='pictures/%Y/%m/%d/', blank=True, null=True)),
                ('picture3', models.ImageField(upload_to='pictures/%Y/%m/%d/', blank=True, null=True)),
                ('picture4', models.ImageField(upload_to='pictures/%Y/%m/%d/', blank=True, null=True)),
                ('picture5', models.ImageField(upload_to='pictures/%Y/%m/%d/', blank=True, null=True)),
                ('services_offered', models.CharField(max_length=255, blank=True, null=True)),
                ('facility_type', models.CharField(max_length=100, blank=True, null=True, choices=[('Public', 'Public'), ('Private', 'Private')])),
                ('road_accessibility', models.BooleanField(default=True)),
                ('adequate_parking', models.BooleanField(default=True)),
                ('electricity', models.BooleanField(default=True)),
                ('clean_water', models.BooleanField(default=True)),
                ('wheelchair_accessible', models.BooleanField(default=True)),
                ('community_healthcare_programs', models.BooleanField(default=True)),
                ('emergencies', models.BooleanField(default=True)),
                ('operating_hrs', models.CharField(max_length=200, blank=True, null=True)),
                ('healthcare_professionals', models.IntegerField(blank=True, null=True)),
                ('amenities_available', models.CharField(max_length=255, blank=True, null=True)),
            ],
            options={
                'db_table': 'kiharu_health_facilities_cleaned',
                'managed': False,
                'verbose_name_plural': 'Kiharu Health Facilities',
            },
        ),
        migrations.CreateModel(
            name='Landmarks',
            fields=[
                ('name', models.CharField(max_length=255, blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(max_length=255, blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, blank=True, null=True)),
            ],
            options={
                'db_table': 'landmarks',
                'managed': False,
                'verbose_name_plural': 'Landmarks',
            },
        ),
    ]

